# Generated by Django 2.2.5 on 2019-12-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='exval',
            fields=[
                ('exval_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('exval_unit', models.CharField(max_length=100)),
                ('exval_ttb', models.FloatField()),
                ('exval_tts', models.FloatField()),
                ('exval_deal', models.FloatField()),
                ('exval_bkpr', models.FloatField()),
                ('exval_kftc_bk', models.FloatField()),
                ('exval_kftc_de', models.FloatField()),
                ('exval_cur_nm', models.CharField(max_length=100)),
            ],
        ),
    ]
