# Generated by Django 2.2.5 on 2019-12-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='memoBoard',
            fields=[
                ('memo_no', models.AutoField(primary_key=True, serialize=False)),
                ('memo_id', models.CharField(max_length=30)),
                ('memo_priority', models.CharField(max_length=30)),
                ('memo_productname', models.CharField(max_length=100)),
                ('memo_cur_unit', models.CharField(max_length=10)),
                ('memo_price', models.FloatField()),
                ('memo_producturl', models.CharField(max_length=2048)),
                ('memo_memo', models.CharField(max_length=100)),
                ('memo_regdate', models.DateTimeField(auto_now_add=True)),
                ('memo_lastdate', models.DateTimeField()),
            ],
        ),
    ]
